root: /eccube-3.0.10/html/
admin_dir: admin/
tpl: /eccube-3.0.10/html/user_data/packages/default/
admin_tpl: /eccube-3.0.10/html/user_data/packages/admin/
image_path: /eccube-3.0.10/html/upload/save_image/
root_dir: /Applications/MAMP/htdocs/eccube-3.0.10
root_urlpath: /eccube-3.0.10/html
template_code: default
admin_route: admin
user_data_route: user_data
public_path: /html
public_path_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/html
image_save_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/html/upload/save_image
image_temp_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/html/upload/temp_image
user_data_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/html/user_data
block_default_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/src/Eccube/Resource/template/default/Block
block_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/app/template/default/Block
template_default_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/src/Eccube/Resource/template/default
template_default_html_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/html/template/default
template_admin_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/src/Eccube/Resource/template/admin
template_admin_html_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/html/template/admin
template_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/app/template/default
template_html_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/html/template/default
template_temp_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/app/cache/eccube/template
csv_temp_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/app/cache/eccube/csv
plugin_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/app/Plugin
plugin_temp_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/app/cache/plugin
plugin_html_realdir: /Applications/MAMP/htdocs/eccube-3.0.10/html/plugin
admin_urlpath: /eccube-3.0.10/html/template/admin
front_urlpath: /eccube-3.0.10/html/template/default
image_save_urlpath: /eccube-3.0.10/html/upload/save_image
image_temp_urlpath: /eccube-3.0.10/html/upload/temp_image
user_data_urlpath: /eccube-3.0.10/html/user_data
plugin_urlpath: /eccube-3.0.10/html/plugin
