<?php

namespace DoctrineProxy\__CG__\Eccube\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \Eccube\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . '_calc', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'stockFinds', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'stocks', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'stockUnlimiteds', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'price01', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'price02', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'price01IncTaxs', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'price02IncTaxs', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'codes', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'classCategories1', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'classCategories2', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'className1', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'className2', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'name', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'note', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'description_list', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'description_detail', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'search_word', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'free_area', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'del_flg', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'create_date', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'update_date', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'ProductCategories', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'ProductClasses', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'CustomerFavoriteProducts', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'Creator', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'Status', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'ProductImage', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'ProductTag');
        }

        return array('__isInitialized__', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . '_calc', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'stockFinds', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'stocks', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'stockUnlimiteds', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'price01', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'price02', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'price01IncTaxs', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'price02IncTaxs', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'codes', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'classCategories1', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'classCategories2', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'className1', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'className2', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'name', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'note', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'description_list', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'description_detail', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'search_word', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'free_area', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'del_flg', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'create_date', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'update_date', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'ProductCategories', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'ProductClasses', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'CustomerFavoriteProducts', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'Creator', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'Status', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'ProductImage', '' . "\0" . 'Eccube\\Entity\\Product' . "\0" . 'ProductTag');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function _calc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '_calc', array());

        return parent::_calc();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnable', array());

        return parent::isEnable();
    }

    /**
     * {@inheritDoc}
     */
    public function getClassName1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassName1', array());

        return parent::getClassName1();
    }

    /**
     * {@inheritDoc}
     */
    public function getClassName2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassName2', array());

        return parent::getClassName2();
    }

    /**
     * {@inheritDoc}
     */
    public function getClassCategories1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassCategories1', array());

        return parent::getClassCategories1();
    }

    /**
     * {@inheritDoc}
     */
    public function getClassCategories2($class_category1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassCategories2', array($class_category1));

        return parent::getClassCategories2($class_category1);
    }

    /**
     * {@inheritDoc}
     */
    public function getStockFind()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockFind', array());

        return parent::getStockFind();
    }

    /**
     * {@inheritDoc}
     */
    public function getStockMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockMin', array());

        return parent::getStockMin();
    }

    /**
     * {@inheritDoc}
     */
    public function getStockMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockMax', array());

        return parent::getStockMax();
    }

    /**
     * {@inheritDoc}
     */
    public function getStockUnlimitedMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockUnlimitedMin', array());

        return parent::getStockUnlimitedMin();
    }

    /**
     * {@inheritDoc}
     */
    public function getStockUnlimitedMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockUnlimitedMax', array());

        return parent::getStockUnlimitedMax();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice01Min()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice01Min', array());

        return parent::getPrice01Min();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice01Max()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice01Max', array());

        return parent::getPrice01Max();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice02Min()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice02Min', array());

        return parent::getPrice02Min();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice02Max()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice02Max', array());

        return parent::getPrice02Max();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice01IncTaxMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice01IncTaxMin', array());

        return parent::getPrice01IncTaxMin();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice01IncTaxMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice01IncTaxMax', array());

        return parent::getPrice01IncTaxMax();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice02IncTaxMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice02IncTaxMin', array());

        return parent::getPrice02IncTaxMin();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice02IncTaxMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice02IncTaxMax', array());

        return parent::getPrice02IncTaxMax();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeMin', array());

        return parent::getCodeMin();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeMax', array());

        return parent::getCodeMax();
    }

    /**
     * {@inheritDoc}
     */
    public function getClassCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassCategories', array());

        return parent::getClassCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function getMainListImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainListImage', array());

        return parent::getMainListImage();
    }

    /**
     * {@inheritDoc}
     */
    public function copy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'copy', array());

        return parent::copy();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', array($note));

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', array());

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionList($descriptionList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionList', array($descriptionList));

        return parent::setDescriptionList($descriptionList);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionList', array());

        return parent::getDescriptionList();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionDetail($descriptionDetail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionDetail', array($descriptionDetail));

        return parent::setDescriptionDetail($descriptionDetail);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionDetail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionDetail', array());

        return parent::getDescriptionDetail();
    }

    /**
     * {@inheritDoc}
     */
    public function setSearchWord($searchWord)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSearchWord', array($searchWord));

        return parent::setSearchWord($searchWord);
    }

    /**
     * {@inheritDoc}
     */
    public function getSearchWord()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSearchWord', array());

        return parent::getSearchWord();
    }

    /**
     * {@inheritDoc}
     */
    public function setFreeArea($freeArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFreeArea', array($freeArea));

        return parent::setFreeArea($freeArea);
    }

    /**
     * {@inheritDoc}
     */
    public function getFreeArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFreeArea', array());

        return parent::getFreeArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelFlg($delFlg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelFlg', array($delFlg));

        return parent::setDelFlg($delFlg);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelFlg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelFlg', array());

        return parent::getDelFlg();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate($createDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', array($createDate));

        return parent::setCreateDate($createDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', array());

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateDate($updateDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateDate', array($updateDate));

        return parent::setUpdateDate($updateDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateDate', array());

        return parent::getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductCategory(\Eccube\Entity\ProductCategory $productCategories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductCategory', array($productCategories));

        return parent::addProductCategory($productCategories);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductCategory(\Eccube\Entity\ProductCategory $productCategories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductCategory', array($productCategories));

        return parent::removeProductCategory($productCategories);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductCategories', array());

        return parent::getProductCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductClass(\Eccube\Entity\ProductClass $productClasses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductClass', array($productClasses));

        return parent::addProductClass($productClasses);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductClass(\Eccube\Entity\ProductClass $productClasses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductClass', array($productClasses));

        return parent::removeProductClass($productClasses);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductClasses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductClasses', array());

        return parent::getProductClasses();
    }

    /**
     * {@inheritDoc}
     */
    public function hasProductClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasProductClass', array());

        return parent::hasProductClass();
    }

    /**
     * {@inheritDoc}
     */
    public function addCustomerFavoriteProduct(\Eccube\Entity\CustomerFavoriteProduct $customerFavoriteProducts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCustomerFavoriteProduct', array($customerFavoriteProducts));

        return parent::addCustomerFavoriteProduct($customerFavoriteProducts);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCustomerFavoriteProduct(\Eccube\Entity\CustomerFavoriteProduct $customerFavoriteProducts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCustomerFavoriteProduct', array($customerFavoriteProducts));

        return parent::removeCustomerFavoriteProduct($customerFavoriteProducts);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerFavoriteProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerFavoriteProducts', array());

        return parent::getCustomerFavoriteProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator(\Eccube\Entity\Member $creator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', array($creator));

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', array());

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(\Eccube\Entity\Master\Disp $status = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductImage(\Eccube\Entity\ProductImage $productImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductImage', array($productImage));

        return parent::addProductImage($productImage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductImage(\Eccube\Entity\ProductImage $productImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductImage', array($productImage));

        return parent::removeProductImage($productImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductImage', array());

        return parent::getProductImage();
    }

    /**
     * {@inheritDoc}
     */
    public function getMainFileName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainFileName', array());

        return parent::getMainFileName();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductTag(\Eccube\Entity\ProductTag $productTag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductTag', array($productTag));

        return parent::addProductTag($productTag);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductTag(\Eccube\Entity\ProductTag $productTag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductTag', array($productTag));

        return parent::removeProductTag($productTag);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductTag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductTag', array());

        return parent::getProductTag();
    }

    /**
     * {@inheritDoc}
     */
    public function offsetExists($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetExists', array($offset));

        return parent::offsetExists($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetSet($offset, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetSet', array($offset, $value));

        return parent::offsetSet($offset, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetGet($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetGet', array($offset));

        return parent::offsetGet($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetUnset($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetUnset', array($offset));

        return parent::offsetUnset($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function setPropertiesFromArray(array $arrProps, array $excludeAttribute = array (
), \ReflectionClass $parentClass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropertiesFromArray', array($arrProps, $excludeAttribute, $parentClass));

        return parent::setPropertiesFromArray($arrProps, $excludeAttribute, $parentClass);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(array $excludeAttribute = array (
), \ReflectionClass $parentClass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($excludeAttribute, $parentClass));

        return parent::toArray($excludeAttribute, $parentClass);
    }

    /**
     * {@inheritDoc}
     */
    public function copyProperties($srcObject, array $excludeAttribute = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'copyProperties', array($srcObject, $excludeAttribute));

        return parent::copyProperties($srcObject, $excludeAttribute);
    }

}
